/*
 * events_saks.h
 *
 *  Created on: 25/03/2026
 *      Author: plibreros
 */

#ifndef INC_EVENTS_SAKS_H_
#define INC_EVENTS_SAKS_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

typedef enum {
	SAKS_ERROR_NO_PARAMS,
	SAKS_ERROR_INIT_PERIPHERALS,
	SAKS_ERROR_INSUFFICIENT_DRIVERS_THERM,
	SAKS_ERROR_METHANE_QA_CMD,
	SAKS_ERROR_MONOXIDE_QA_CMD,
	SAKS_ERROR_QUEUE_LCD,
	SAKS_ERROR_QUEUE_MQTT,
	SAKS_ERROR_MQTT_NO_AVAILABLE,
	SAKS_ERROR_THERM_SHORTED,
	SAKS_ERROR_THERM_OUT_RANGE,
	SAKS_ERROR_EXCEEDED_ATTMS_CO,
	SAKS_ERROR_EXCEEDED_ATTMS_CH4,
	SAKS_ERROR_MAX_THERM_SHORTED,
	SAKS_ERROR_TRANSVR_I2C_NO_RESP,
} _errors_events;

typedef enum {
	SAKS_STATUS_PWR_SUPPLY,
	SAKS_STATUS_ALM_SIG,
	SAKS_STATUS_BATTERY,
	SAKS_STATUS_CH4,
	SAKS_STATUS_WWIFI,
	SAKS_STATUS_MQTT,
	SAKS_STATUS_ALM_BUTT_ACTIVE,
	SAKS_STATUS_CH4_LEVEL_ALARM,
	SAKS_STATUS_CO_LEVEL_ALARM,
	SAKS_STATUS_CH1_OVERTEMP_ALARM,
	SAKS_STATUS_CH2_OVERTEMP_ALARM,
	SAKS_STATUS_CH3_OVERTEMP_ALARM
} _status_events;

/*define Errors*/
#define FSAKS_ERROR_NO_PARAMS					(1 << SAKS_ERROR_NO_PARAMS)
#define FSAKS_ERROR_INIT_PERIPHERALS			(1 << SAKS_ERROR_INIT_PERIPHERALS)
#define FSAKS_ERROR_INSUFFICIENT_DRIVERS_THERM	(1 << SAKS_ERROR_INSUFFICIENT_DRIVERS_THERM)
#define FSAKS_ERROR_METHANE_QA_CMD				(1 << SAKS_ERROR_METHANE_QA_CMD)
#define FSAKS_ERROR_MONOXIDE_QA_CMD				(1 << SAKS_ERROR_MONOXIDE_QA_CMD)
#define FSAKS_ERROR_QUEUE_LCD					(1 << SAKS_ERROR_QUEUE_LCD)
#define FSAKS_ERROR_QUEUE_MQTT					(1 << SAKS_ERROR_QUEUE_MQTT)
#define FSAKS_ERROR_MQTT_NO_AVAILABLE			(1 << SAKS_ERROR_MQTT_NO_AVAILABL)
#define FSAKS_ERROR_THERM_SHORTED				(1 << SAKS_ERROR_THERM_SHORTED)
#define FSAKS_ERROR_THERM_OUT_RANGE				(1 << SAKS_ERROR_THERM_OUT_RANGE)
#define FSAKS_ERROR_EXCEEDED_ATTMS_CO			(1 << SAKS_ERROR_EXCEEDED_ATTMS_CO)
#define FSAKS_ERROR_EXCEEDED_ATTMS_CH4			(1 << SAKS_ERROR_EXCEEDED_ATTMS_CH4)
#define FSAKS_ERROR_MAX_THERM_SHORTED			(1 << SAKS_ERROR_MAX_THERM_SHORTED)
#define FSAKS_ERROR_TRANSVR_I2C_NO_RESP			(1 << SAKS_ERROR_TRANSVR_I2C_NO_RESP)
/*define Events*/
#define FSAKS_STATUS_PWR_SUPPLY					(1 << SAKS_STATUS_PWR_SUPPLY)
#define FSAKS_STATUS_ALM_SIG					(1 << SAKS_STATUS_ALM_SIG)
#define FSAKS_STATUS_BATTERY					(1 << SAKS_STATUS_BATTERY)
#define FSAKS_STATUS_CH4						(1 << SAKS_STATUS_CH4)
#define FSAKS_STATUS_WWIFI						(1 << SAKS_STATUS_WWIFI)
#define FSAKS_STATUS_MQTT						(1 << SAKS_STATUS_MQTT)
#define FSAKS_STATUS_ALM_BUTT_ACTIVE			(1 << SAKS_STATUS_ALM_BUTT_ACTIVE)
#define FSAKS_STATUS_CH4_LEVEL_ALARM			(1 << SAKS_STATUS_CH4_LEVEL_ALARM)
#define FSAKS_STATUS_CO_LEVEL_ALARM				(1 << SAKS_STATUS_CO_LEVEL_ALARM)
#define FSAKS_STATUS_CH1_OVERTEMP_ALARM			(1 << SAKS_STATUS_CH1_OVERTEMP_ALARM)
#define FSAKS_STATUS_CH2_OVERTEMP_ALARM			(1 << SAKS_STATUS_CH2_OVERTEMP_ALARM)
#define FSAKS_STATUS_CH3_OVERTEMP_ALARM			(1 << SAKS_STATUS_CH3_OVERTEMP_ALARM)

#ifdef __cplusplus
}
#endif

#endif /* INC_EVENTS_SAKS_H_ */
